server:
  port: 9092
  servlet:
    context-path: /connection-builder-service
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:flightdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect