server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: master-data-service
          uri: 'http://localhost:9091'
          predicates:
            - Path=/master-data-service/**
        - id: connection-builder-service
          uri: 'http://localhost:9092'
          predicates:
            - Path=/connection-builder-service/**